[package]
name = "hblank-dogfood-hblank-preview"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
gpui = { version = "0.2.2", features = ["test-support"] }
hblank = { path = "../../../crates/hblank", features = ["test-support"] }
hblank_project = { package = "hblank-dogfood", path = ".." }

