[package]
name = "hblank"
description = "Develop GPUI components in isolation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[features]
default = ["crates-io-gpui"]
crates-io-gpui = ["dep:gpui-crates-io"]
zed-gpui = ["dep:gpui-zed", "dep:gpui-platform-zed"]

[dependencies]
gpui-crates-io = { package = "gpui", version = "0.2.2", optional = true }
gpui-zed = { package = "gpui", git = "https://github.com/zed-industries/zed", rev = "d9ad6aff67e47de43abb270d22de75dd950f1b48", optional = true }
gpui-platform-zed = { package = "gpui_platform", git = "https://github.com/zed-industries/zed", rev = "d9ad6aff67e47de43abb270d22de75dd950f1b48", features = ["font-kit", "wayland", "x11"], optional = true }
hblank-macros = { path = "../hblank-macros", version = "0.1.1" }
inventory.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true

[lints]
workspace = true
