[package]
name = "hblank"
description = "Develop GPUI components in isolation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[features]
test-support = ["gpui/test-support"]

[dependencies]
gpui.workspace = true
hblank-core = { path = "../hblank-core", version = "0.4.2" }
hblank-macros = { path = "../hblank-macros", version = "0.4.2" }
inventory.workspace = true
serde.workspace = true
toml.workspace = true

[lints]
workspace = true
