#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
REPOSITORY="mmmeff/hblank"
WORKFLOW="release.yml"

banner "Hblank release setup"

stage "Bootstrap crates.io token"
say "The first release needs a temporary crates.io token because Trusted Publishing can only be configured after each crate exists."
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI must be installed and authenticated before setup can continue."
  exit 1
fi
actual_repository="$(gh repo view --json nameWithOwner --jq .nameWithOwner)"
if [[ "$actual_repository" != "$REPOSITORY" ]]; then
  warn "Run this wizard from the $REPOSITORY checkout, not $actual_repository."
  exit 1
fi
open_url "https://crates.io/settings/tokens/new"
step "Create a token named 'hblank GitHub bootstrap'."
step "Choose the shortest expiry that leaves time to merge and run the initial release."
step "Enable publish-new and publish-update. New crate names cannot use per-crate ownership scopes yet."
ask_secret CRATES_IO_TOKEN "Paste the new crates.io token:"
if [[ -z "$CRATES_IO_TOKEN" ]]; then
  warn "The token cannot be empty."
  exit 1
fi
set_secret CARGO_REGISTRY_TOKEN "$CRATES_IO_TOKEN"
unset CRATES_IO_TOKEN
if [[ "$(gh secret list --repo "$REPOSITORY" --json name --jq 'any(.name == "CARGO_REGISTRY_TOKEN")')" != "true" ]]; then
  warn "GitHub secret CARGO_REGISTRY_TOKEN was not created."
  exit 1
fi
note "GitHub secret CARGO_REGISTRY_TOKEN is ready."

stage "Grant release workflow write access"
open_url "https://github.com/$REPOSITORY/settings/actions"
step "Under Workflow permissions, select Read and write permissions."
step "Save the change."
pause "Press Enter after the permission is saved."

stage "Pre-1.0 baseline tag"
say "semantic-release starts at 1.0.0 without history. A v0.0.0 tag on the root commit makes the existing feat commit release 0.1.0."
root_commit="$(git rev-list --max-parents=0 HEAD)"
local_baseline="$(git rev-list -n 1 v0.0.0 2>/dev/null || true)"
remote_baseline=""
while read -r hash _; do remote_baseline="$hash"; done < <(git ls-remote --tags origin refs/tags/v0.0.0 2>/dev/null || true)
if [[ -n "$local_baseline" && "$local_baseline" != "$root_commit" ]]; then
  warn "Local v0.0.0 points to $local_baseline instead of root commit $root_commit."
  exit 1
fi
if [[ -n "$remote_baseline" && "$remote_baseline" != "$root_commit" ]]; then
  warn "Remote v0.0.0 points to $remote_baseline instead of root commit $root_commit."
  exit 1
fi
if [[ -z "$remote_baseline" ]]; then
  if confirm "Push v0.0.0 at root commit $root_commit to origin?"; then
    [[ -n "$local_baseline" ]] || git tag v0.0.0 "$root_commit"
    git push origin refs/tags/v0.0.0
  else
    warn "The release workflow will reject an initial release without this tag."
    exit 1
  fi
else
  note "origin already has the correct v0.0.0 baseline tag."
fi

stage "Initial automated release"
say "The release workflow must be present on main before it can publish 0.1.0."
open_url "https://github.com/$REPOSITORY/actions/workflows/$WORKFLOW"
step "Merge or push this release-automation change to main, then return here."
pause "Press Enter once $WORKFLOW is visible on the main branch."
gh workflow run "$WORKFLOW" --repo "$REPOSITORY" --ref main
sleep 3
initial_run_id="$(gh run list --repo "$REPOSITORY" --workflow "$WORKFLOW" --branch main --event workflow_dispatch --limit 1 --json databaseId --jq '.[0].databaseId')"
if [[ -z "$initial_run_id" ]]; then
  warn "GitHub did not return the dispatched release run."
  exit 1
fi
gh run watch "$initial_run_id" --repo "$REPOSITORY" --exit-status
say "The hblank-core, hblank-macros, hblank, and hblank-cli 0.1.0 crates should now exist."

stage "Trust hblank-core workflow"
open_url "https://crates.io/crates/hblank-core/settings"
step "Open Trusted Publishers and add a GitHub Actions publisher."
step "Owner: mmmeff; repository: hblank; workflow: release.yml; environment: leave blank."
pause "Press Enter after the hblank-core publisher is saved."

stage "Trust hblank-macros workflow"
open_url "https://crates.io/crates/hblank-macros/settings"
step "Open Trusted Publishers and add a GitHub Actions publisher."
step "Owner: mmmeff; repository: hblank; workflow: release.yml; environment: leave blank."
pause "Press Enter after the hblank-macros publisher is saved."

stage "Trust hblank workflow"
open_url "https://crates.io/crates/hblank/settings"
step "Open Trusted Publishers and add a GitHub Actions publisher."
step "Owner: mmmeff; repository: hblank; workflow: release.yml; environment: leave blank."
pause "Press Enter after the hblank publisher is saved."

stage "Trust hblank-cli workflow"
open_url "https://crates.io/crates/hblank-cli/settings"
step "Open Trusted Publishers and add a GitHub Actions publisher."
step "Owner: mmmeff; repository: hblank; workflow: release.yml; environment: leave blank."
pause "Press Enter after the hblank-cli publisher is saved."

stage "Remove bootstrap token and verify OIDC"
say "Every crate name must now exist and have a Trusted Publisher entry."
if ! confirm "Delete the CARGO_REGISTRY_TOKEN bootstrap secret now?"; then
  warn "Trusted Publishing cannot be verified while the bootstrap token exists."
  exit 1
fi
gh secret delete CARGO_REGISTRY_TOKEN --repo "$REPOSITORY"
WRITTEN_SECRET=()
note "The bootstrap secret is deleted. Future releases must use short-lived OIDC credentials."
gh workflow run "$WORKFLOW" --repo "$REPOSITORY" --ref main
sleep 3
verification_run_id="$(gh run list --repo "$REPOSITORY" --workflow "$WORKFLOW" --branch main --event workflow_dispatch --limit 1 --json databaseId --jq '.[0].databaseId')"
if [[ -z "$verification_run_id" ]]; then
  warn "GitHub did not return the dispatched verification run."
  exit 1
fi
gh run watch "$verification_run_id" --repo "$REPOSITORY" --exit-status
verification_log="$(gh run view "$verification_run_id" --repo "$REPOSITORY" --log)"
if [[ "$verification_log" != *"Using a short-lived crates.io trusted-publishing token"* ]]; then
  warn "The workflow did not use a short-lived crates.io trusted-publishing token."
  exit 1
fi
note "Future releases will use only short-lived OIDC credentials."

finish
